import React, { useState } from 'react';
import { router } from 'expo-router';
import { Button, Choice, Copy, Field, Message, Rule, Screen, Section } from '../../components/ui';
import { useDemo } from '../../state/demo';
export default function Me() {
  const { state, updateProfile, setTheme, renew, logout } = useDemo(); const [name, setName] = useState(state.user?.displayName ?? ''); const [drink, setDrink] = useState(state.user?.drinkPreference ?? ''); const [message, setMessage] = useState(''); const [renewal, setRenewal] = useState(false); const [leaving, setLeaving] = useState(false);
  function save() { if (!name.trim()) { setMessage('A preferred name is required.'); return; } updateProfile(name, drink); setMessage('Preferences saved on this device.'); }
  return <Screen eyebrow="MAKE YOURSELF AT HOME" title="Me."><Field label="Preferred name" value={name} onChangeText={setName} maxLength={40} /><Field label="Preferred drink" value={drink} onChangeText={setDrink} maxLength={80} /><Copy kind="small">In the future, reception can prepare your usual drink. This preview keeps preferences on this device only.</Copy><Button solid title="Save preferences" onPress={save} />{message && <Message>{message}</Message>}<Section><Copy kind="heading">Membership.</Copy><Copy>{state.membership?.memberNo} · {state.membership?.status}</Copy><Copy kind="small">Preview renewal date: {state.membership?.renewsAt ? new Date(state.membership.renewsAt).toLocaleDateString('en-MY') : 'Not set'}. Membership price awaits confirmation.</Copy><Button title="Open membership card" onPress={() => router.push('/membership')} />{renewal ? <><Copy>Extend this demo membership by 30 days? No charge will be made.</Copy><Button title="Confirm simulated renewal" onPress={() => { renew(); setRenewal(false); setMessage('Demo membership extended by 30 days. No payment collected.'); }} /><Button title="Keep current membership" onPress={() => setRenewal(false)} /></> : <Button title="Try membership renewal" onPress={() => setRenewal(true)} />}</Section><Section><Copy kind="heading">Appearance.</Copy>{(['system', 'light', 'dark'] as const).map(mode => <Choice key={mode} title={mode === 'system' ? 'Use device setting' : mode === 'light' ? 'Paper' : 'Night'} selected={state.theme === mode} onPress={() => setTheme(mode)} />)}<Rule /><Copy>Language: English</Copy><Copy kind="small">Preview privacy: no analytics, uploads or external account. Local demo records and preferences are cleared when you sign out. Do not enter confidential information.</Copy>{leaving ? <><Copy>Sign out and clear this device's demo records?</Copy><Button title="Confirm sign out" onPress={() => void logout().then(() => router.replace('/onboarding'))} /><Button title="Stay signed in" onPress={() => setLeaving(false)} /></> : <Button title="Sign out and clear preview" onPress={() => setLeaving(true)} />}</Section></Screen>;
}
