import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildCjkFonts } from '@drprop/brand/fonts/cjk-subset';
import { defineConfig, type Plugin } from 'vite';
import { pages, renderDocument } from './src/render/page.ts';

const root = fileURLToPath(new URL('.', import.meta.url));
const brandFile = (name: string) => fileURLToPath(new URL(`../brand/logo/${name}`, import.meta.url));

/**
 * Chinese fonts: Noto SC subset to exactly the characters on the Chinese pages
 * (see brand/fonts/cjk-subset.ts). Written before Vite reads the CSS.
 */
async function writeCjkFonts() {
  const cssFile = fileURLToPath(new URL('./src/styles/cjk.generated.css', import.meta.url));
  const outDir = fileURLToPath(new URL('./src/styles/cjk-fonts', import.meta.url));
  const html = pages.filter((p) => p.lang === 'zh').map((p) => renderDocument(p, ''));
  const strip = (s: string) => s.replace(/<[^>]+>/g, ' ');
  const serifText = html
    .flatMap((h) => [...h.matchAll(/<(\w+)[^>]*class="[^"]*\bdisplay\b[^"]*"[^>]*>([\s\S]*?)<\/\1>/g)].map((m) => m[2]!))
    .map(strip)
    .join(' ');
  const r = await buildCjkFonts({
    serifText,
    sansText: html.map(strip).join(' '),
    outDir,
    toUrl: (abs) => relative(dirname(cssFile), abs).split('\\').join('/'),
  });
  writeFileSync(
    cssFile,
    `/* Generated by vite.config.ts: ${r.files} subset files, ${(r.bytes / 1024).toFixed(1)} KB (from ${r.slicesTotal} Noto SC slices). Do not edit. */\n${r.css}\n`,
  );
}
await writeCjkFonts();

/** The inline header logo: sized by CSS, hidden from AT (the link carries the name). */
const inlineLogo = () =>
  readFileSync(brandFile('logo.svg'), 'utf8')
    .replace(/<title>.*?<\/title>\s*/s, '')
    .replace(/ width="[^"]*" height="[^"]*"/, '')
    .replace(/ role="img" aria-label="[^"]*"/, ' class="brand__logo" aria-hidden="true" focusable="false"')
    .trim();

/**
 * Each page is a near-empty HTML shell on disk (so Vite's dev server and build
 * both see it); this plugin replaces the shell with the rendered page for its
 * language. Dictionaries: src/i18n/*.json. No i18n framework.
 */
const entryFor = (filename: string) => {
  const rel = relative(root, filename).split('\\').join('/');
  return pages.find((p) => p.file === rel);
};

function drpropPages(): Plugin {
  return {
    name: 'drprop-pages',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        const entry = entryFor(ctx.filename);
        return entry ? renderDocument(entry, inlineLogo()) : html;
      },
    },
    configureServer(server) {
      server.middlewares.use('/favicon.svg', (_req, res) => {
        res.setHeader('Content-Type', 'image/svg+xml');
        res.end(readFileSync(brandFile('favicon.svg')));
      });
    },
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: 'favicon.svg', source: readFileSync(brandFile('favicon.svg')) });
    },
  };
}

/** Preload the display face that draws the LCP headline. */
function preloadDisplayFont(): Plugin {
  return {
    name: 'drprop-preload-display-font',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler(_html, ctx) {
        // Chinese pages: the headline is set in the (tiny) Noto Serif SC subsets instead.
        const zh = entryFor(ctx.filename)?.lang === 'zh';
        const pattern = zh ? /noto-serif-sc-[\w-]+\.woff2$/ : /instrument-serif-latin-400-normal-[\w-]+\.woff2$/;
        return Object.keys(ctx.bundle ?? {})
          .filter((f) => pattern.test(f))
          .map((file) => ({
            tag: 'link',
            attrs: { rel: 'preload', as: 'font', type: 'font/woff2', href: `/${file}`, crossorigin: '' },
            injectTo: 'head' as const,
          }));
      },
    },
  };
}

export default defineConfig({
  root,
  plugins: [drpropPages(), preloadDisplayFont()],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    // Never inline fonts as base64: most Noto SC slices are never downloaded.
    assetsInlineLimit: 0,
    rollupOptions: {
      input: Object.fromEntries(pages.map((p) => [p.file.replace(/\/?index\.html$/, '') || 'index', `${root}${p.file}`])),
    },
  },
});
