import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync } from 'node:zlib';
import { buildCjkFonts } from '@drprop/brand/fonts/cjk-subset';
import { defineConfig, type Plugin } from 'vite';
import { launchProblems, site } from './src/config/site.ts';
import { pages, renderDocument } from './src/render/page.ts';

const root = fileURLToPath(new URL('.', import.meta.url));
const brandFile = (name: string) => fileURLToPath(new URL(`../brand/logo/${name}`, import.meta.url));

/**
 * Chinese fonts: Noto SC subset to exactly the characters on the Chinese pages
 * (see brand/fonts/cjk-subset.ts). Written before Vite reads the CSS.
 */
async function writeCjkFonts() {
  const cssFile = fileURLToPath(new URL('./src/styles/cjk.generated.css', import.meta.url));
  const outDir = fileURLToPath(new URL('./src/styles/cjk-fonts', import.meta.url));
  const html = pages.filter((p) => p.lang === 'zh').map((p) => renderDocument(p, ''));
  const strip = (s: string) => s.replace(/<[^>]+>/g, ' ');
  const serifText = html
    .flatMap((h) => [...h.matchAll(/<(\w+)[^>]*class="[^"]*\bdisplay\b[^"]*"[^>]*>([\s\S]*?)<\/\1>/g)].map((m) => m[2]!))
    .map(strip)
    .join(' ');
  const r = await buildCjkFonts({
    serifText,
    sansText: html.map(strip).join(' '),
    outDir,
    toUrl: (abs) => relative(dirname(cssFile), abs).split('\\').join('/'),
  });
  writeFileSync(
    cssFile,
    `/* Generated by vite.config.ts: ${r.files} subset files, ${(r.bytes / 1024).toFixed(1)} KB (from ${r.slicesTotal} Noto SC slices). Do not edit. */\n${r.css}\n`,
  );
}
await writeCjkFonts();

/** The inline header logo: sized by CSS, hidden from AT (the link carries the name). */
const inlineLogo = () =>
  readFileSync(brandFile('logo.svg'), 'utf8')
    .replace(/<title>.*?<\/title>\s*/s, '')
    .replace(/ width="[^"]*" height="[^"]*"/, '')
    .replace(/ role="img" aria-label="[^"]*"/, ' class="brand__logo" aria-hidden="true" focusable="false"')
    .trim();

/**
 * Each page is a near-empty HTML shell on disk (so Vite's dev server and build
 * both see it); this plugin replaces the shell with the rendered page for its
 * language. Dictionaries: src/i18n/*.json. No i18n framework.
 */
const entryFor = (filename: string) => {
  const rel = relative(root, filename).split('\\').join('/');
  return pages.find((p) => p.file === rel);
};

function drpropPages(): Plugin {
  return {
    name: 'drprop-pages',
    transformIndexHtml: {
      order: 'pre',
      handler(html, ctx) {
        const entry = entryFor(ctx.filename);
        return entry ? renderDocument(entry, inlineLogo()) : html;
      },
    },
    configureServer(server) {
      server.middlewares.use('/favicon.svg', (_req, res) => {
        res.setHeader('Content-Type', 'image/svg+xml');
        res.end(readFileSync(brandFile('favicon.svg')));
      });
    },
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: 'favicon.svg', source: readFileSync(brandFile('favicon.svg')) });
    },
  };
}

/** Preload the display face that draws the LCP headline. */
function preloadDisplayFont(): Plugin {
  return {
    name: 'drprop-preload-display-font',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler(_html, ctx) {
        // Chinese pages: the headline is set in the (tiny) Noto Serif SC subsets instead.
        const zh = entryFor(ctx.filename)?.lang === 'zh';
        const pattern = zh ? /noto-serif-sc-[\w-]+\.woff2$/ : /instrument-serif-latin-400-normal-[\w-]+\.woff2$/;
        return Object.keys(ctx.bundle ?? {})
          .filter((f) => pattern.test(f))
          .map((file) => ({
            tag: 'link',
            attrs: { rel: 'preload', as: 'font', type: 'font/woff2', href: `/${file}`, crossorigin: '' },
            injectTo: 'head' as const,
          }));
      },
    },
  };
}

/** Setting site.origin means launch: refuse to build while placeholders remain. */
function launchGuard(): Plugin {
  return {
    name: 'drprop-launch-guard',
    apply: 'build',
    buildStart() {
      const problems = launchProblems();
      if (site.origin && problems.length) {
        this.error(`site.origin is set, so this is a launch build, but placeholders remain:\n  ${problems.join('\n  ')}`);
      }
      if (!site.origin && problems.length) this.info(`Preview build: ${problems.length} placeholders in src/config/site.ts.`);
    },
  };
}

/**
 * /third-party-notices.txt: the licences of everything the site ships (fonts, three.js,
 * Lenis, the fluid simulation, GSAP), read from the installed packages so versions
 * stay current. The OFL and MIT licences require the notice to travel with the files.
 */
function thirdPartyNotices(): Plugin {
  const require = createRequire(import.meta.url);
  // Some packages (three) don't export package.json: find it above the entry point.
  const pkg = (name: string) => {
    let dir = dirname(require.resolve(name));
    for (;;) {
      try {
        const json = JSON.parse(readFileSync(`${dir}/package.json`, 'utf8')) as { name?: string; version: string; license: string };
        if (json.name === name) return { dir, ...json };
      } catch {
        // no package.json at this level
      }
      const up = dirname(dir);
      if (up === dir) throw new Error(`package.json for ${name} not found`);
      dir = up;
    }
  };
  const fromPackage = (name: string, what: string) => {
    const p = pkg(name);
    return { title: `${name} ${p.version} (${p.license})`, what, text: readFileSync(`${p.dir}/LICENSE`, 'utf8') };
  };
  return {
    name: 'drprop-notices',
    apply: 'build',
    generateBundle() {
      const sections = [
        fromPackage('@fontsource/instrument-serif', 'Instrument Serif, the display face'),
        fromPackage('@fontsource/geist', 'Geist, the text face'),
        fromPackage('@fontsource/geist-mono', 'Geist Mono, for numbers'),
        fromPackage('@fontsource/noto-sans-sc', 'Noto Sans SC, subset for the Chinese pages'),
        fromPackage('@fontsource/noto-serif-sc', 'Noto Serif SC, subset for the Chinese pages'),
        fromPackage('three', 'three.js, the Pulse Roof line'),
        fromPackage('lenis', 'Lenis, smooth scrolling'),
        {
          title: 'WebGL-Fluid-Simulation by Pavel Dobryakov (MIT)',
          what: 'the ink fluid, ported and modified (web/src/scene/fluid)',
          text: readFileSync(fileURLToPath(new URL('./src/scene/fluid/LICENSE', import.meta.url)), 'utf8'),
        },
        {
          title: `gsap ${pkg('gsap').version} with ScrollTrigger`,
          what: 'scroll-linked animation',
          text: 'Copyright GreenSock. Used under the GSAP Standard "No Charge" License: https://gsap.com/standard-license\n',
        },
      ];
      const body = sections
        .map((x) => `${x.title}\n${x.what}\n${'-'.repeat(72)}\n${x.text.trim()}\n`)
        .join('\n\n');
      this.emitFile({
        type: 'asset',
        fileName: 'third-party-notices.txt',
        source: `Dr Prop website: third-party software and fonts\n\n${body}`,
      });
    },
  };
}

/**
 * Brief §7.4: all JavaScript together under 250 KB gzipped. Prints each chunk and
 * fails the build when the total goes over.
 */
function jsBudget(limitKb = 250): Plugin {
  return {
    name: 'drprop-js-budget',
    apply: 'build',
    generateBundle(_options, bundle) {
      const chunks = Object.values(bundle)
        .filter((f) => f.type === 'chunk')
        .map((c) => ({ file: c.fileName, gz: gzipSync(c.code, { level: 9 }).length }))
        .sort((a, b) => b.gz - a.gz);
      const total = chunks.reduce((sum, c) => sum + c.gz, 0);
      const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;
      // The HTML entries leave near-empty chunks that Vite drops later: count them, don't list them.
      const lines = chunks
        .filter((c) => c.gz >= 512)
        .map((c) => `  ${c.file.padEnd(40)} ${kb(c.gz).padStart(9)}`)
        .join('\n');
      const summary = `JavaScript, gzipped: ${kb(total)} of ${limitKb} KB (brief §7.4)\n${lines}`;
      if (total > limitKb * 1024) this.error(`Over budget. ${summary}`);
      this.info(summary);
    },
  };
}

export default defineConfig({
  root,
  plugins: [launchGuard(), drpropPages(), preloadDisplayFont(), jsBudget(), thirdPartyNotices()],
  build: {
    // three.js is one lazy chunk of ~550 KB raw (~135 KB gzipped). The budget that
    // matters is the gzipped total, checked by jsBudget().
    chunkSizeWarningLimit: 600,
    outDir: 'dist',
    emptyOutDir: true,
    // Never inline fonts as base64: most Noto SC slices are never downloaded.
    assetsInlineLimit: 0,
    rollupOptions: {
      input: Object.fromEntries(pages.map((p) => [p.file.replace(/\/?index\.html$/, '') || 'index', `${root}${p.file}`])),
    },
  },
});
